service:
  name: ChefDeskWebApi

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: categories
          parameters:
            querystrings:
              tenantId: true
          cors: true
      - http:
          method: get
          path: item/{id}
          request:
            parameters:
              paths:
                id: true
              querystrings:
                tenantId: true
          cors: true
      - http:
          method: get
          path: menu
          parameters:
            querystrings:
              tenantId: true
          cors: true
