service:
  name: PopeyesUaeWebApi

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: categories
      - http:
          method: get
          path: item/{id}